USE DATABASE CANCERANALYTICSDB;

INSERT INTO CancerAnalyticsDB.TransformedData.DemographicDim (DemographicKey, Sex, AgeGroup)
SELECT
    DENSE_RANK() OVER (ORDER BY Sex, AgeGroup) AS DemographicKey,
    Sex,
    AgeGroup
FROM (
    SELECT DISTINCT Sex, AgeGroup FROM CANCERANALYTICSDB.RAWDATA.RAWINCIDENCE
    UNION
    SELECT DISTINCT Sex, AgeGroup FROM CANCERANALYTICSDB.RAWDATA.RAWMORTALITY
    UNION
    SELECT DISTINCT Sex, AgeGroup FROM CANCERANALYTICSDB.RAWDATA.RAWSURVIVAL
) AS Combinations;

INSERT INTO CancerAnalyticsDB.TransformedData.CancerTypeDim (CancerTypeKey, CancerGroupSite, ICD10Codes)
SELECT
    DENSE_RANK() OVER (ORDER BY CancerGroupSite, ICD10Codes) AS CancerTypeKey,
    CancerGroupSite,
    ICD10Codes
FROM (
    SELECT DISTINCT CANCERGROUPSITE, ICD10CODES FROM CANCERANALYTICSDB.RAWDATA.RAWINCIDENCE
    UNION
    SELECT DISTINCT CANCERGROUPSITE, ICD10CODES FROM CANCERANALYTICSDB.RAWDATA.RAWMORTALITY
    UNION
    SELECT DISTINCT CANCERGROUPSITE, ICD10CODES FROM CANCERANALYTICSDB.RAWDATA.RAWSURVIVAL
    UNION
    SELECT DISTINCT CANCERGROUPSITE, ICD10CODES FROM CANCERANALYTICSDB.RAWDATA.RAWINCIDENCEBYTERRITORY
) AS Combinations;