snowsql_config_path = "~/.snowsql/config"
snowsql_connection_name = "dev"

[default]
input_parameters = "()"
return_type = "string"
file = "app.zip"
name = "update_fact_sp"
handler = "app.main"
execute_as_caller = true

[dev]
database = "HOL_DB"
schema = "TRANSFORMED_DATA"
warehouse = "HOL_WH"
role = "HOL_ROLE"
overwrite = true
