-- ----------------------------------------------------------------------------
-- Step #2: Create the account level objects
-- ----------------------------------------------------------------------------

-- Roles
SET MY_USER = CURRENT_USER();
CREATE OR REPLACE ROLE HOL_ROLE;
GRANT ROLE HOL_ROLE TO ROLE SYSADMIN;
GRANT ROLE HOL_ROLE TO USER IDENTIFIER($MY_USER);

GRANT EXECUTE TASK ON ACCOUNT TO ROLE HOL_ROLE;
GRANT MONITOR EXECUTION ON ACCOUNT TO ROLE HOL_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE HOL_ROLE;

-- Databases
CREATE OR REPLACE DATABASE CANCERANALYTICS_DB;
GRANT OWNERSHIP ON DATABASE CANCERANALYTICS_DB TO ROLE HOL_ROLE;

-- Warehouses
CREATE OR REPLACE WAREHOUSE HOL_WH WAREHOUSE_SIZE = XSMALL, AUTO_SUSPEND = 300, AUTO_RESUME= TRUE;
GRANT OWNERSHIP ON WAREHOUSE HOL_WH TO ROLE HOL_ROLE;

-- ----------------------------------------------------------------------------
-- Step #3: Create the database level objects
-- ----------------------------------------------------------------------------
USE ROLE HOL_ROLE;
USE WAREHOUSE HOL_WH;
USE DATABASE CANCERANALYTICS_DB;

-- Schemas
CREATE OR REPLACE SCHEMA EXTERNAL;
CREATE OR REPLACE SCHEMA RAW_DATA;
CREATE OR REPLACE SCHEMA TEMP;
CREATE OR REPLACE SCHEMA TRANSFORMED_DATA;

-- External  objects
USE SCHEMA EXTERNAL;
CREATE OR REPLACE FILE FORMAT CANCERANALYTICS_DB.EXTERNAL.CSV_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = '|' 
    RECORD_DELIMITER = '\n'
    SKIP_HEADER = 1
;
CREATE OR REPLACE STAGE CANCERANALYTICS_DB.EXTERNAL.RAW_DATA_STAGE
    file_format = CSV_FORMAT
;

PUT file:///Users/gilbertharlimputra/Desktop/GitHub/cancer_dashboard_pipeline/data/transformed/incidence.csv @CANCERANALYTICS_DB.EXTERNAL.RAW_DATA_STAGE;
PUT file:///Users/gilbertharlimputra/Desktop/GitHub/cancer_dashboard_pipeline/data/transformed/mortality.csv @CANCERANALYTICS_DB.EXTERNAL.RAW_DATA_STAGE;
PUT file:///Users/gilbertharlimputra/Desktop/GitHub/cancer_dashboard_pipeline/data/transformed/survival.csv @CANCERANALYTICS_DB.EXTERNAL.RAW_DATA_STAGE;
PUT file:///Users/gilbertharlimputra/Desktop/GitHub/cancer_dashboard_pipeline/data/transformed/incidence_territory.csv @CANCERANALYTICS_DB.EXTERNAL.RAW_DATA_STAGE;
PUT file:///Users/gilbertharlimputra/Desktop/GitHub/cancer_dashboard_pipeline/data/transformed/incidence_new.csv @CANCERANALYTICS_DB.EXTERNAL.RAW_DATA_STAGE;
PUT file:///Users/gilbertharlimputra/Desktop/GitHub/cancer_dashboard_pipeline/data/transformed/mortality_new.csv @CANCERANALYTICS_DB.EXTERNAL.RAW_DATA_STAGE;
PUT file:///Users/gilbertharlimputra/Desktop/GitHub/cancer_dashboard_pipeline/data/transformed/incidence_territory_new.csv @CANCERANALYTICS_DB.EXTERNAL.RAW_DATA_STAGE;

USE SCHEMA RAW_DATA;
CREATE OR REPLACE TABLE CANCERANALYTICS_DB.RAW_DATA.INCIDENCE (
	DATA_TYPE VARCHAR(50),
	CANCER_GROUP_SITE VARCHAR(255),
	YEAR INT,
	SEX VARCHAR(20),
	AGE_GROUP_YEARS VARCHAR(50),
	COUNT INT
);

CREATE OR REPLACE TABLE CANCERANALYTICS_DB.RAW_DATA.MORTALITY (
	DATA_TYPE VARCHAR(50),
	CANCER_GROUP_SITE VARCHAR(255),
	YEAR INT,
	SEX VARCHAR(20),
	AGE_GROUP_YEARS VARCHAR(50),
	COUNT INT
);

CREATE OR REPLACE TABLE CANCERANALYTICS_DB.RAW_DATA.SURVIVAL (
	SURVIVAL_TYPE VARCHAR(50),
	CANCER_GROUP_SITE VARCHAR(255),
	PERIOD_YEARS VARCHAR(50),
	SEX VARCHAR(20),
	YEARS_AFTER_DIAGNOSIS INT,
	AGE_GROUP_YEARS VARCHAR(50),
	SURVIVAL FLOAT,
	"95_CI_LOWER_BOUND" FLOAT,
	"95_CI_UPPER_BOUND" FLOAT
);

CREATE OR REPLACE TABLE CANCERANALYTICS_DB.RAW_DATA.INCIDENCE_TERRITORY (
	DATA_TYPE VARCHAR(50),
	CANCER_GROUP_SITE VARCHAR(255),
	YEAR INT,
	SEX VARCHAR(20),
	STATE_OR_TERRITORY VARCHAR(50),
	COUNT INT
);

-- Transformed Data Tables
-- USE SCHEMA TRANSFORMED_DATA;

-- Table for Cancer Data Types
-- CREATE OR REPLACE TABLE CANCERANALYTICS_DB.TRANSFORMED_DATA.DATA_TYPE (
--     DATA_TYPE_ID INT PRIMARY KEY,
--     DATA_TYPE_NAME VARCHAR(20) UNIQUE NOT NULL
-- );
-- -- Table for Cancer Group Types
-- CREATE OR REPLACE TABLE CANCERANALYTICS_DB.TRANSFORMED_DATA.CANCER_GROUP_SITE (
--     CANCER_GROUP_ID INT PRIMARY KEY,
--     CANCER_GROUP_SITE_NAME VARCHAR(255) UNIQUE NOT NULL
-- );

-- -- Table for Sex Types
-- CREATE OR REPLACE TABLE CANCERANALYTICS_DB.TRANSFORMED_DATA.SEX (
--     SEX_ID INT PRIMARY KEY,
--     SEX_TYPE VARCHAR(50) NOT NULL
-- );

-- -- Table for Age Groups
-- CREATE OR REPLACE TABLE CANCERANALYTICS_DB.TRANSFORMED_DATA.AGE_GROUP (
--     AGE_GROUP_ID INT PRIMARY KEY,
--     AGE_GROUP_YEARS VARCHAR(50) NOT NULL
-- );

-- -- Table for States or Territories (If applicable)
-- CREATE OR REPLACE TABLE CANCERANALYTICS_DB.TRANSFORMED_DATA.STATE_TERRITORY (
--     STATE_TERRITORY_ID INT PRIMARY KEY,
--     STATE_OR_TERRITORY_NAME VARCHAR(100) NOT NULL
-- );

-- -- Table for Incidence Data
-- CREATE OR REPLACE TABLE CANCERANALYTICS_DB.TRANSFORMED_DATA.INCIDENCE (
--     INCIDENCE_ID INT PRIMARY KEY,
--     DATA_TYPE_ID INT,
--     CANCER_GROUP_ID INT,
--     YEAR INT,
--     SEX_ID INT,
--     AGE_GROUP_ID INT,
--     COUNT INT,
--     FOREIGN KEY (DATA_TYPE_ID) REFERENCES CANCERANALYTICS_DB.TRANSFORMED_DATA.DATA_TYPE(DATA_TYPE_ID),
--     FOREIGN KEY (CANCER_GROUP_ID) REFERENCES CANCERANALYTICS_DB.TRANSFORMED_DATA.CANCER_GROUP_SITE(CANCER_GROUP_ID),
--     FOREIGN KEY (SEX_ID) REFERENCES CANCERANALYTICS_DB.TRANSFORMED_DATA.SEX(SEX_ID),
--     FOREIGN KEY (AGE_GROUP_ID) REFERENCES CANCERANALYTICS_DB.TRANSFORMED_DATA.AGE_GROUP(AGE_GROUP_ID)
-- );

-- -- Table for Mortality Data
-- CREATE OR REPLACE TABLE CANCERANALYTICS_DB.TRANSFORMED_DATA.MORTALITY (
--     MORTALITY_ID INT PRIMARY KEY,
--     DATA_TYPE_ID INT,
--     CANCER_GROUP_ID INT,
--     YEAR INT,
--     SEX_ID INT,
--     AGE_GROUP_ID INT,
--     COUNT INT,
--     FOREIGN KEY (DATA_TYPE_ID) REFERENCES CANCERANALYTICS_DB.TRANSFORMED_DATA.DATA_TYPE(DATA_TYPE_ID),
--     FOREIGN KEY (CANCER_GROUP_ID) REFERENCES CANCERANALYTICS_DB.TRANSFORMED_DATA.CANCER_GROUP_SITE(CANCER_GROUP_ID),
--     FOREIGN KEY (SEX_ID) REFERENCES CANCERANALYTICS_DB.TRANSFORMED_DATA.SEX(SEX_ID),
--     FOREIGN KEY (AGE_GROUP_ID) REFERENCES CANCERANALYTICS_DB.TRANSFORMED_DATA.AGE_GROUP(AGE_GROUP_ID)
-- );

-- -- Table for Survival Data
-- CREATE TABLE CANCERANALYTICS_DB.TRANSFORMED_DATA.SURVIVAL (
--     SURVIVAL_ID INT PRIMARY KEY,
--     DATA_TYPE_ID INT,
--     CANCER_GROUP_ID INT,
--     PERIOD_YEARS VARCHAR(50),
--     SEX_ID INT,
--     YEARS_AFTER_DIAGNOSIS INT,
--     AGE_GROUP_ID INT,
--     SURVIVAL_RATE DECIMAL(5,4),
--     "95_CI_LOWER_BOUND" DECIMAL(5,4),
--     "95_CI_UPPER_BOUND" DECIMAL(5,4),
--     FOREIGN KEY (DATA_TYPE_ID) REFERENCES CANCERANALYTICS_DB.TRANSFORMED_DATA.DATA_TYPE(DATA_TYPE_ID),
--     FOREIGN KEY (CANCER_GROUP_ID) REFERENCES CANCERANALYTICS_DB.TRANSFORMED_DATA.CANCER_GROUP_SITE(CANCER_GROUP_ID),
--     FOREIGN KEY (SEX_ID) REFERENCES CANCERANALYTICS_DB.TRANSFORMED_DATA.SEX(SEX_ID),
--     FOREIGN KEY (AGE_GROUP_ID) REFERENCES CANCERANALYTICS_DB.TRANSFORMED_DATA.AGE_GROUP(AGE_GROUP_ID)
-- );

-- -- Table for Incidence by Territory Data
-- CREATE OR REPLACE TABLE CANCERANALYTICS_DB.TRANSFORMED_DATA.INCIDENCE_TERRITORY (
--     INCIDENCE_TERRITORY_ID INT PRIMARY KEY,
--     DATA_TYPE_ID INT,
--     CANCER_GROUP_ID INT,
--     SEX_ID INT,
--     STATE_TERRITORY_ID INT,
--     YEAR INT,
--     COUNT INT,
--     FOREIGN KEY (DATA_TYPE_ID) REFERENCES CANCERANALYTICS_DB.TRANSFORMED_DATA.DATA_TYPE(DATA_TYPE_ID),
--     FOREIGN KEY (CANCER_GROUP_ID) REFERENCES CANCERANALYTICS_DB.TRANSFORMED_DATA.CANCER_GROUP_SITE(CANCER_GROUP_ID),
--     FOREIGN KEY (SEX_ID) REFERENCES CANCERANALYTICS_DB.TRANSFORMED_DATA.SEX(SEX_ID),
--     FOREIGN KEY (STATE_TERRITORY_ID) REFERENCES CANCERANALYTICS_DB.TRANSFORMED_DATA.STATE_TERRITORY(STATE_TERRITORY_ID)
-- );