USE ROLE HOL_ROLE;
USE WAREHOUSE HOL_WH;
USE SCHEMA CANCERANALYTICS_DB.TRANSFORMED_DATA;

-- ----------------------------------------------------------------------------
-- Create the tasks to call our Python stored procedures
-- ----------------------------------------------------------------------------
CREATE OR REPLACE TASK TRANSFORM_DATA_TASK
WAREHOUSE = HOL_WH
WHEN 
    SYSTEM$STREAM_HAS_DATA('CANCERANALYTICS_DB.RAW_DATA.RAW_INCIDENCE_STREAM')
    OR
    SYSTEM$STREAM_HAS_DATA('CANCERANALYTICS_DB.RAW_DATA.RAW_MORTALITY_STREAM')
    OR
    SYSTEM$STREAM_HAS_DATA('CANCERANALYTICS_DB.RAW_DATA.RAW_TERRITORY_STREAM')
    OR
    SYSTEM$STREAM_HAS_DATA('CANCERANALYTICS_DB.RAW_DATA.RAW_SURVIVAL_STREAM')
AS
CALL CANCERANALYTICS_DB.RAW_DATA.TRANSFORM_DATA_SP();

CREATE OR REPLACE TASK UPDATE_DIMENSION_TASK
WAREHOUSE = HOL_WH
AS
CALL CANCERANALYTICS_DB.RAW_DATA.UPDATE_DIMENSION_SP();

CREATE OR REPLACE TASK UPDATE_FACT_TASK
WAREHOUSE = HOL_WH
AS
CALL CANCERANALYTICS_DB.RAW_DATA.UPDATE_FACT_SP();

CREATE OR REPLACE TASK UPDATE_DASH_VIEW_TASK
WAREHOUSE = HOL_WH
AS
CALL CANCERANALYTICS_DB.RAW_DATA.UPDATE_DASH_VIEW_SP();

-- ----------------------------------------------------------------------------
-- Execute the tasks
-- ----------------------------------------------------------------------------

EXECUTE TASK CANCERANALYTICS_DB.TRANSFORMED_DATA.TRANSFORM_DATA_TASK;
EXECUTE TASK CANCERANALYTICS_DB.TRANSFORMED_DATA.UPDATE_DIMENSION_TASK;
EXECUTE TASK CANCERANALYTICS_DB.TRANSFORMED_DATA.UPDATE_FACT_TASK;
EXECUTE TASK CANCERANALYTICS_DB.TRANSFORMED_DATA.UPDATE_DASH_VIEW_TASK;